### ISSUE TITLE
展示有问题

### ISSUE THREAD

**Issue by zhangyanjie666** [lchenfox/react-native-common-date-picker#1]
展示不全，有时候只展示月份，有时候是年份，年月日展示随机

**Comment by arlovip** [comment]
> 展示不全，有时候只展示月份，有时候是年份，年月日展示随机

可以提供一下系统（Android还是iOS）、RN版本的相关信息吗？是模拟器还是真机？我这边试了下没问题，方便的话也可以提供下代码和相关截图。

**Comment by zhangyanjie666** [comment]
> > 展示不全，有时候只展示月份，有时候是年份，年月日展示随机
> 
> 可以提供一下系统（Android还是iOS）、RN版本的相关信息吗？是模拟器还是真机？我这边试了下没问题，方便的话也可以提供下代码和相关截图。

iOS系统，模拟器 ，iPhone 11 Pro Max，13.3.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-03 at 10 44 04](https://user-images.githubusercontent.com/33825747/86426397-2b364e00-bd1a-11ea-823a-92c0d877f77c.png)

下面是代码:
<Modal
                            animationType="fade"
                            transparent={true}
                            visible={this.state.modalVisibleDate}

                            onRequestClose={() => { this.onRequestClose() }}

                        >
                            <View style={{ flex: 1,backgroundColor: 'rgba(0,0,0,0.1)', justifyContent: "center" }}>

                                <DatePicker
                                    defaultDate={"2015-06-30"}
                                    
                                    confirm={date => {
                                        console.warn(date)
                                        this.setState({
                                            modalVisibleDate: false,
                                        })
                                    }}
                                />
                            </View>


                        </Modal>

**Comment by arlovip** [comment]
@zhangyanjie666 抱歉，我使用你的代码，系统、模拟器测试，并未复现你说的问题，见截图：

![date-picker-screenshot.png](https://i.loli.net/2020/07/05/7JiRV8OcqsDnMEf.png)

另外我发布了新版本，你可以使用最新版本尝试一下，若还有问题，请告诉我，我将继续跟进，谢谢。

**Comment by zhangyanjie666** [comment]
> @zhangyanjie666 抱歉，我使用你的代码，系统、模拟器测试，并未复现你说的问题，见截图：
> 
> ![date-picker-screenshot.png](https://camo.githubusercontent.com/23fa1d7c6de243cceba20002b129afdd99b1ef96/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f30352f374a695256384f637173446e4d45662e706e67)
> 
> 另外我发布了新版本，你可以使用最新版本尝试一下，若还有问题，请告诉我，我将继续跟进，谢谢。

我更新成了你的最新的版本，这个版本是没有之前的那个问题的，是正常的

**Comment by arlovip** [comment]
好的👌，那issue关闭了。
