### ISSUE TITLE
Day and date values do not match when used with negative offset timezones

### ISSUE THREAD

**Issue by Tanuja0049** [lchenfox/react-native-common-date-picker#10]
version: 2.3.4

Issue:
•	When the device is set in a negative offset time-zone, we observed that for any date the day is shown ahead of the actual day. i.e. 20 November 2021 is shown on Friday instead of Saturday. 
•	For a positive offset time-zone, we observed that it is displayed correctly. 

Here are two screen shots:

![Negative_Offset](https://user-images.githubusercontent.com/35992503/143591971-1bdbc33b-37e4-472a-854e-8f96b6f1f227.PNG)
![positive_offset](https://user-images.githubusercontent.com/35992503/143591976-8a3c2083-75c4-44ea-baf8-4c507ce82d83.PNG)

**Comment by arlovip** [comment]
@Tanuja0049 Thanks for your report. It has been fixed in `v2.3.6` now.
