### ISSUE TITLE
CalendarList doesn't focus on current date

### ISSUE THREAD

**Issue by Gr3at** [lchenfox/react-native-common-date-picker#14]
Hello,

I am trying to make the `CalendarList` to focus on a specific date upon appearance by setting `defaultDates` to some value, 
but the component keeps focusing on the `minDate`. The code below is what i use.

```javascript

<CalendarList
    containerStyle={{ flex: 1 }}
    titleText="Select Date"
    showToolBar={false}
    cancel={() => setVisibleCallendar(false)}
    onPressDate={(date) => {
        setSelectedCalendarDate(date);
        setVisibleCallendar(false);
    }}
    minDate={'2021-01-01'}
    maxDate={new Date()}
    defaultDates={[new Date(), new Date()]}
/>
```

In my opinion the expected behavior of a datepicker is to show the current date on render not the `minDate`.

Is there any way to achieve this?

I'm on version: 2.3.6

---
## Update - Workaround

I found this in the CalendarList source code:
https://github.com/lchenfox/react-native-common-date-picker/blob/4c2d29266eea19a4f1124a31d279c81370877a8a/src/calendar/CalendarList.js#L128-L131

I am using functional components with hooks so i added a `React.useRef` along with `<CalendarList ref={calendarRef} ....otherprops` on the component.

Even though this works, i still believe that it would be good to be able to define the initial focus date as part of the provided props.

**Comment by arlovip** [comment]
@Gr3at Thanks for the suggestion. Glad that you got it work. I'll take it into consideration in later versions.

**Comment by dhairyasenjaliya** [comment]
hello having still same problem even tried scrollToEnd() but no luck

**Comment by dhairyasenjaliya** [comment]
@lchenfox please add getItemLayout into Flatlist in calanderList in order to work scrollToEnd(
<img width="947" alt="Screenshot 2022-04-27 at 3 01 29 PM" src="https://user-images.githubusercontent.com/47522946/165488692-74e53cdf-c3c9-4165-a161-5e1706258c8c.png">
)
