### ISSUE TITLE
Friday & Saturday are missing from calendar 

### ISSUE THREAD

**Issue by Salman98** [lchenfox/react-native-common-date-picker#16]
can check is something need to add in this ? 

 <CalendarList
                            firstDayOnWeeks={0}
                            showWeeks={false}
                            minDate='2022-01-01'
                            maxDate={new Date()}
                            containerStyle={{ flex: 1 }}
                            cancel={() => toggleModel(false)}
                            confirm={data => {
                                toggleModel(false);
                                onDateChange(data[0], data[1])
                            }}
                            toolBarPosition="bottom"
                            confirmText="Apply"
                        />

**Comment by arlovip** [comment]
> 

Sorry I can't reproduce your issue with the given code snippets. If you'd like to show week  days, perhaps you can try to set `showWeeks={true}`. By the way, `firstDayOnWeeks={0}` is the default value that means the 1st of each month starts from `Sunday`. Or I have misunderstood what you meant? If so, please provide a screenshot or any more details. Thanks.
