### ISSUE TITLE
Default Date not seleceted 

### ISSUE THREAD

**Issue by dhairyasenjaliya** [lchenfox/react-native-common-date-picker#18]
defaultDates={[new Date(), new Date() ]}
after passing this parameter by default not getting selected
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-26 at 09 52 18](https://user-images.githubusercontent.com/47522946/165220777-b94fbf63-985b-4808-9830-627a6a6baea7.png)

**Comment by arlovip** [comment]
@dhairyasenjaliya hi, I can't reproduce your issue. Code snippets as follows:

```
<CalendarList
    horizontal={true}
    defaultDates={[new Date(), new Date()]}
    minDate='2022-04-01'  
/>               
```

So can you give more details about that? Or show your code snippets if possible.

**Comment by dhairyasenjaliya** [comment]
solved it in latest version
