### ISSUE TITLE
react-native-common-date-picker模块引入时报错

### ISSUE THREAD

**Issue by myselfyy** [lchenfox/react-native-common-date-picker#19]
通过yarn add方式引入，在页面中使用import方式使用时，报错：react-native-common-date-picker模块找不到

**Comment by arlovip** [comment]
@myselfyy 抱歉，最近太忙了。这边创建了新项目，使用`yarn add react-native-common-date-picker`安装后没有复现你说的问题，版本如下

```
  "dependencies": {
    "react": "18.0.0",
    "react-native": "0.69.1",
    "react-native-common-date-picker": "^2.3.7"
  }
```

确保安装成功，并且正确引入`import {DatePicker} from "react-native-common-date-picker";`。这应该和该库没有关系，先关闭这个问题，如果你还遇到同样的问题，请打开这个`issue`并提供更多的信息。

**Comment by myselfyy** [comment]
感谢反馈！
我发现问题了 ，因为这组件通过纯js开发，而我项目里使用ts开发，所以不兼容
