### ISSUE TITLE
老兄，datePicker/DatePicker.js 里面能不能修改一点，兼容更多版本？

### ISSUE THREAD

**Issue by tyawei** [lchenfox/react-native-common-date-picker#23]
139行，176行，<>  </> 这个修改下，用View吧，我这儿RN 0.55版本报错。
我自己版本低？？我也没办法啊，公司就是这么用的。
其他地方也顺便看看吧，拜托。。

**Comment by arlovip** [comment]
@tyawei 抱歉，最近有事，已经修复。

**Comment by arlovip** [comment]
> @tyawei 抱歉，最近有事，已经修复。

最新版本 `2.3.9` 。

**Comment by tyawei** [comment]
多谢咯，东西还是不错的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lchenfox/react-native-common-date-picker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月17日(星期四) 晚上11:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lchenfox/react-native-common-date-picker] 老兄，datePicker/DatePicker.js 里面能不能修改一点，兼容更多版本？ (Issue #23)





  
@tyawei 抱歉，最近有事，已经修复。
  
最新版本 2.3.9 。
