### ISSUE TITLE
How to get selected value when showToolBar is false in DatePicker?

### ISSUE THREAD

**Issue by vickywsy** [lchenfox/react-native-common-date-picker#7]
I hide the default toolbar to use to customized toolbar,  how to make it work with the date picker?

**Comment by arlovip** [comment]
@vickywsy Hi, toolbar now is not supported to customize and not associated with DatePicker. Maybe it'll be implemented later. Now, v2.3.4 was released. A `onValueChange` function is added. You can use this to get the selected date in real time like

```
...
onValueChange={selectedDate => console.warn('You can get the selected date here, date: ', date)}
...
```

As for customized toolbar mentioned above, you can do as follows

```
let selectedCurrentDate = '';

...
this.state = {
     selectedDate: ''
}
...

<CustomizedToolBar  // The customized tool bar by you.
     cancel={()=> {}} 
     confirm={() => {
            this.setState({selectedDate:  selectedCurrentDate});
     }}
>
<DatePicker 
     onValueChange={selectedDate => {
           selectedCurrentDate = selectedDate;
     }}
/>
```
